name: gamelib
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  http: ^0.13.5
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/icons/
  fonts:
    - family : Copperplate Gothic Bold
      fonts:
        - asset: assets/fonts/Copperplate Gothic Bold/copperplategothic_bold.ttf
    