POST http://localhost:5291/api/games
Content-Type: application/json

{
  "name": "Grand Theft Auto V",
  
  "releaseDate": "2013-09-17",
  
  "backgroundImageUrl" : "https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg",
  "metaCritic" : 92
}
###
GET http://localhost:5291/api/games?pageCount=20
###
GET http://localhost:5291/api/games?pageNumber=20
###
GET http://localhost:5291/api/games?pageNumber=1&pageCount=5
###
POST http://localhost:5291/api/genres
Content-Type: application/json

{
  "name": "dummy"
}
###
GET https://api.rawg.io/api/games?key=6b5fcc8fe6c748eaac97665e86118d6f&metacritic="80-100"&page_size=100&page=2
###
GET https://api.rawg.io/api/genres?key=6b5fcc8fe6c748eaac97665e86118d6f
###
GET http://localhost:5291/api/games
###
GET http://localhost:5291/api/games/4875
###
POST http://localhost:5291/api/games
Content-Type: application/json

{
  "name" : "DUMMY",
  "genreIds" : [8],
  "platformIds" :[37],
  "releaseDate" :"1999-12-12",
  "metaCritic" : 0
}
###
DELETE http://localhost:5291/api/games/4876
###
PUT http://localhost:5291/api/games/4876
Content-Type: application/json

{
  "name": "DUMMY2",
  "releaseDate": "1999-12-12",
  "genreIds" :[10],
  "platformIds" :[35],
  "metaCritic": 0,
  "backgroundImageUrl": "null"
}
###
GET http://localhost:5291/api/games?dates=2020-12-12,2021-12-12&orderings=metacritic&
###
POST http://localhost:5291/api/genres 
Content-Type: application/json

{
  "name":"Action"
}
###
GET http://localhost:5291/api/genres
###
PUT http://localhost:5291/api/genres/9
Content-Type: application/json

{
  "name":"Action"
}